### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by Eleftheriaexarchou** [Eleftheriaexarchou/Earthscan_validation#2]
This is the collaborative env I was referring to : @katherinecrichton  @fnavi  can you see this? Do you think convenient to have chats here?

**Comment by fnavi** [comment]
Not sure if everytime someone comments - we will get an email :/

**Comment by Eleftheriaexarchou** [comment]
This is not a chat to react immediately so an email is perfect. OK I will give it a try and create issues related to EarthScan, when there is a bug etc , to allow us to keep track ... I am not expert in this but I know gitlab has been amazinfg tool in the last and I think github has similar functionality
